# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Which descriptions this issue's reports claim, and what one has to say.

A description is the one place this workflow both edits and may find a report
living in, so the claim is asked of every record that can hold one -- damaged
ones included -- and the closing reference is read as GitHub reads it.
"""

from __future__ import annotations

import unittest
from dataclasses import replace
from types import MappingProxyType, SimpleNamespace

from orchestrator.github.pinned_state import PinnedState
from orchestrator.github.pull_request_reports import ReportLocation
from orchestrator.workflow.engine import (
    report_delivery_state as _delivery_state,
    report_locations as _locations,
    report_record_state as _record_state,
    report_records as _records,
)
from tests.workflow.engine import (
    report_delivery_test_support as delivery_support,
    report_record_test_support as record_support,
    report_settled_fixture as settled_fixture,
    report_transaction_test_support as support,
)

ISSUE = 12

SLUG = "owner/repository"

OTHER_ISSUE = 13

ATTRIBUTION = "Generated by orchestrator (claude session `sess`)."

# The description of the pull request every record here is about, and the same
# pull request's comment, which no body edit can reach.
ON_THE_DESCRIPTION = ReportLocation(pr_number=support.PR_NUMBER)

IN_A_COMMENT = ReportLocation(
    pr_number=support.PR_NUMBER, comment_id=settled_fixture.COMMENT_ID,
)

# A record whose location still reads while the rest of it will not, and one
# that names no readable place at all.
DAMAGED_ON = MappingProxyType({
    "location_pr": support.PR_NUMBER, "location_comment": None,
})

DAMAGED_ELSEWHERE = MappingProxyType({
    "location_pr": support.OTHER_PR_NUMBER, "location_comment": None,
})

UNREADABLE = "not a record"

FIXES = f"Fixes #{ISSUE}"

# Every way Markdown or HTML shows a reference literally, or hides it: GitHub
# acts on none of them. Quoted code is still code.
SHOWN_AS_CODE = (
    f"```\n{FIXES}\n```",
    f"Write `{FIXES}` to close it.",
    f"    {FIXES}",
    f">     {FIXES}",
    f"> ~~~\n> {FIXES}\n> ~~~",
    f"> > ```\n> > {FIXES}",
    f"-     {FIXES}",
    f"<pre>{FIXES}</pre>",
    f"<PRE lang='text'>\n{FIXES}\n</PRE>",
    f"<code>{FIXES}</code>",
    f"<pre>\n{FIXES}",
    f"<!-- {FIXES} -->",
    # An escaped backtick is a literal character, so it opens no span and the
    # real one after it still encloses the reference; an escaped BACKSLASH
    # leaves the backtick behind it a real opener.
    f"Escaped \\` then `{FIXES}`.",
    f"A backslash \\\\`{FIXES}`",
)

# The same reference as prose, which a quote or a list item still is.
SHOWN_AS_PROSE = (
    FIXES,
    f"> {FIXES}",
    f"- {FIXES}",
    f"<details>{FIXES}</details>",
    f"<pre>an example</pre>\n\n{FIXES}",
    # The escaped backtick pairs with nothing, so it hides nothing either; and
    # inside a span a backslash escapes nothing, so that span ends where it says.
    f"A literal \\` and then {FIXES}, with `code` after.",
    f"`a\\` {FIXES} `b`",
    f"`unclosed {FIXES}",
)


# The publication the settled pair below is about, and the same publication
# with each member of it moved in turn.
SUBJECT = record_support.PUBLISHED.subject

NAMED = (SUBJECT.repo_slug, SUBJECT.pr_number, SUBJECT.branch, SUBJECT.source_sha)

OTHER_PUBLICATIONS = (
    ("someone/else", *NAMED[1:]),
    (NAMED[0], support.OTHER_PR_NUMBER, *NAMED[2:]),
    (*NAMED[:2], "another-branch", NAMED[3]),
    (*NAMED[:3], support.MOVED_SHA),
)


def _verified_at(location: ReportLocation) -> dict:
    """The pinned comment of an issue whose three records all name `location`."""
    state = PinnedState()
    _delivery_state.record_delivered_report(
        state, replace(delivery_support.ASSERTED, location=location),
    )
    _record_state.record_pending_report(
        state, replace(record_support.VERIFIED, location=location),
    )
    settled_fixture.records_current(state, SUBJECT, 1, location=location)
    return dict(state.data)


def _claims(carried: dict) -> tuple:
    """Whether `carried` claims this description, and the other one's."""
    state = PinnedState(state_data=carried)
    return (
        _locations.claims_the_description(state, support.PR_NUMBER),
        _locations.claims_the_description(state, support.OTHER_PR_NUMBER),
    )


def _handed_off(revision: int = 1, **carried) -> PinnedState:
    """A comment carrying the handoff of `revision`, beside anything else."""
    state = PinnedState(state_data=carried)
    settled_fixture.records_handoff(
        state, support.RECEIPT, revision, SUBJECT.source_sha,
    )
    return state


class ClaimedDescriptionTest(unittest.TestCase):
    def test_each_record_claims_what_it_names(self) -> None:
        # Delivered, pending and settled each claim it alone, since the claim
        # outlives each separately; the same records in a comment claim
        # nothing a body edit can reach, and an issue carrying none claims none.
        for key, recorded in _verified_at(ON_THE_DESCRIPTION).items():
            with self.subTest(record=key):
                self.assertEqual(_claims({key: recorded}), (True, False))
        self.assertEqual(_claims(_verified_at(IN_A_COMMENT)), (False, False))
        self.assertEqual(_claims({}), (False, False))

    def test_a_damaged_record_claims_what_it_may(self) -> None:
        # A record nobody can read claims the description unless the place it
        # still names is readably elsewhere -- and so does a settled pair
        # missing its current report, unless the handoff names another PR.
        dangling = dict(_handed_off().data)
        for damaged, claimed in (
            ({_records.DELIVERED_REPORT: dict(DAMAGED_ON)}, (True, False)),
            ({_records.PENDING_REPORT: dict(DAMAGED_ELSEWHERE)}, (False, True)),
            ({_records.CURRENT_REPORT: UNREADABLE}, (True, True)),
            (dangling, (True, False)),
            ({**dangling, _records.CURRENT_REPORT: None}, (True, False)),
        ):
            with self.subTest(damaged=sorted(damaged)):
                self.assertEqual(_claims(damaged), claimed)

    def test_only_an_unnamed_description_costs(self) -> None:
        # The collision is exactly a report on THIS description while it does
        # not close the issue and name the session.
        on_it = SimpleNamespace(location=ON_THE_DESCRIPTION)
        for record, described, costs in (
            (on_it, False, True),
            (on_it, True, False),
            (SimpleNamespace(location=IN_A_COMMENT), False, False),
            (SimpleNamespace(location=None), False, False),
        ):
            with self.subTest(record=record, described=described):
                self.assertEqual(
                    _locations.costs_the_description(
                        record, support.PR_NUMBER, described,
                    ),
                    costs,
                )


class SettledPublicationTest(unittest.TestCase):
    def test_the_pair_answers_for_what_it_names(self) -> None:
        # Both settled records, agreeing, and every member of the subject: a
        # pair about another repository, pull request, branch or commit -- or
        # one whose handoff is missing, or disagrees -- answers for nothing.
        lone = PinnedState()
        settled_fixture.records_current(lone, SUBJECT, 1)
        settled = _handed_off(**lone.data)
        disagreeing = _handed_off(settled_fixture.NEXT_REVISION, **lone.data)

        self.assertEqual(
            _locations.settled_publication(settled, *NAMED).subject, SUBJECT,
        )
        for asked in OTHER_PUBLICATIONS:
            with self.subTest(asked=asked):
                self.assertIsNone(_locations.settled_publication(settled, *asked))
        for unsettled in (lone, disagreeing):
            self.assertIsNone(_locations.settled_publication(unsettled, *NAMED))


class DescribesTheIssueTest(unittest.TestCase):
    def test_every_closing_spelling_github_honours(self) -> None:
        # Bare and repository-qualified references both close this issue --
        # the qualifier compared as GitHub compares it, without case -- while
        # one naming another repository, or another number, closes nothing
        # here. Without the attribution no reference is enough.
        for reference, signed, closes in (
            (FIXES, ATTRIBUTION, True),
            (f"resolves: Owner/Repository#{ISSUE}", ATTRIBUTION, True),
            (f"Closes someone/else#{ISSUE}", ATTRIBUTION, False),
            (f"Fixes #{OTHER_ISSUE}", ATTRIBUTION, False),
            (FIXES, "", False),
        ):
            with self.subTest(reference=reference, signed=bool(signed)):
                self.assertEqual(_describes(reference, signed), closes)

    def test_a_reference_shown_as_code_closes_nothing(self) -> None:
        # Literal code is text GitHub does not act on, quoted or not; the same
        # reference as prose -- in a quote, a list item, beside code -- does.
        for shown, closes in (
            *((reference, False) for reference in SHOWN_AS_CODE),
            *((reference, True) for reference in SHOWN_AS_PROSE),
        ):
            with self.subTest(shown=shown):
                self.assertEqual(_describes(shown, ATTRIBUTION), closes)


def _describes(reference: str, signed: str) -> bool:
    """Whether a description of `reference` above `signed` names the issue."""
    return _locations.describes_the_issue(
        SimpleNamespace(body=f"{signed}\n\n{reference}"), ISSUE, ATTRIBUTION, SLUG,
    )


if __name__ == "__main__":
    unittest.main()
