# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Which closing references are certainly prose, whichever way Markdown is read.

Held against the closing pattern itself rather than against the text left over,
since what matters is whether a reference GitHub shows as code is ever read as
one that closes the issue. Each case is one way a reading can go wrong: a
container it does not see through, a block it does not see begin, a delimiter
it pairs that Markdown does not.
"""

from __future__ import annotations

import unittest
from types import SimpleNamespace

from orchestrator.workflow.engine import (
    report_code_spans as _code_spans,
    report_locations as _locations,
)

ISSUE = 12

SLUG = "owner/repository"

ATTRIBUTION = "Generated by orchestrator (claude session `sess`)."

FIXES = f"Fixes #{ISSUE}"

# Code by the line it stands on: fenced or indented, behind any nesting of list
# and blockquote markers. A fence closes only behind the markers it opened
# behind, so a quoted run inside an unquoted fence closes nothing.
CODE_LINES = (
    f"```\n{FIXES}\n```",
    f"    {FIXES}",
    f">     {FIXES}",
    f"> ~~~\n> {FIXES}\n> ~~~",
    f"> > ```\n> > {FIXES}",
    f"-     {FIXES}",
    f"- -     {FIXES}",
    f"- > ~~~\n  > {FIXES}\n  > ~~~",
    f"> - ~~~\n>   {FIXES}\n>   ~~~",
    f"~~~\n> ~~~\n{FIXES}\n~~~",
    # Markdown ends a line on a bare carriage return too, and on the pair.
    f"Intro\r\r    {FIXES}",
    f"Intro\r\n\r\n    {FIXES}",
    f"~~~\r{FIXES}\r~~~",
)

# Code by the span it stands in. An escaped backtick is a literal character and
# opens nothing, while an escaped BACKSLASH leaves the backtick behind it a real
# opener. Spans pair within one block, and a block can begin with no blank line
# above it -- on a heading, say -- so a span is looked for from every line.
CODE_SPANS = (
    f"Write `{FIXES}` to close it.",
    f"Escaped \\` then `{FIXES}`.",
    f"A backslash \\\\`{FIXES}`",
    f"An unmatched ` here.\n\n`{FIXES}`",
    f"# A ` heading\n`Fixes\n#{ISSUE}`",
    f"`\n*\n{FIXES}`",
    f"foo `\n    ~~~\n    bar\n    ~~~\n{FIXES}`",
)

# Code, or hidden, by the HTML around it, read off the text as written: an
# element is literal whether or not some reading pairs a backtick across its
# opening tag. Nested tags are counted, a stray closing tag closes nothing, and
# neither does one a code span or a comment may hide.
CODE_IN_HTML = (
    f"<pre>{FIXES}</pre>",
    f"<PRE lang='text'>\n{FIXES}\n</PRE>",
    f"<code>{FIXES}</code>",
    f"<pre>\n{FIXES}",
    f"<!-- {FIXES} -->",
    f"`unmatched\n<pre>` {FIXES}</pre>",
    f"<code><code>example</code> {FIXES}</code>",
    f"<pre><code>example</code> {FIXES}</pre>",
    f"<pre></code> {FIXES}</pre>",
    f"text <pre>`</pre> `{FIXES}`",
    f"<pre><!-- </pre> --> {FIXES}</pre>",
    f"<textarea>{FIXES}</textarea>",
    f"<pre {FIXES}",
    # A tag is read as HTML reads one: a `>` or a closing tag inside a quoted
    # attribute value ends nothing, and a value never closed takes the rest.
    f'<pre data-example="> </pre>">{FIXES}</pre>',
    f"<pre data-example='> </pre>'>{FIXES}</pre>",
    f'<pre data-example="x> </pre> {FIXES}',
)

# A tag quoted as code is no tag only where the code is CERTAIN. Not after a
# `<` that may have taken the backtick into a tag of its own; not in a fence an
# HTML block may hold, one Markdown closes sooner than the strict reading, or a
# quoted one a blank line ended; and never inside an element already open.
UNCERTAIN_QUOTING = (
    f'see <a title="`"><pre>` {FIXES}',
    f"<div>\n```\n<pre>\n```\n</div>\n\n{FIXES}",
    f"~~~\nx\n ~~~\n<pre>\n~~~\n{FIXES}",
    f"> ```\n\n> <pre>\n> ```\n> {FIXES}",
    f"<pre>\n\n`<pre>` x</pre> {FIXES}</pre>",
    # A quoted tag is passed over at its name, never read on to a `>` of its
    # own: cut short inside its code, it would take the real tag after that
    # code as its attributes, and hide the element that opens.
    f"Example `<pre` then <code>{FIXES}</code>",
    f"Example `</pre` then <pre>{FIXES}</pre>",
    f"Example `<!--` then <code>{FIXES}</code>",
    f"```\n<pre\n```\n\n<code>{FIXES}</code>",
)

# No reference at all, however the text around it reads: a keyword parted from
# its number by code, and one inside a tag's own markup.
NO_REFERENCE = (
    f"Fixes `a span` #{ISSUE}",
    f"Fixes\n    an indented line\n#{ISSUE}",
    f'<a title="{FIXES}">a link</a>',
    f'<a title="> {FIXES}">a link</a>',
    f'<div title="{FIXES}',
)

# The same reference as prose, which a quote or a list item still is. A stray
# backtick pairs with nothing past its own block, an escaped one with nothing at
# all, and inside a span a backslash escapes nothing, so that span ends where it
# says. A fence closed behind its own markers has ended.
PROSE = (
    FIXES,
    f"> {FIXES}",
    f"- {FIXES}",
    f"<details>{FIXES}</details>",
    f"<pre>an example</pre>\n\n{FIXES}",
    f"See `one`. {FIXES}. Also `another`.",
    f"A literal \\` and then {FIXES}, with `code` after.",
    f"`a\\` {FIXES} `b`",
    f"`unclosed {FIXES}",
    f"An unmatched ` here.\n\n{FIXES}",
    f"> ```\n> an example\n> ```\n\n{FIXES}",
    f"```html\n<pre>\nan example\n</pre>\n```\n\n{FIXES}",
    f"<!-- a note --> {FIXES}",
    f"{FIXES}\n\nWrap it in `<pre>`.",
    f"Intro\r\r{FIXES}",
    # A tag quoted as an example, in a span or a closed fence that is code
    # however the text is read, opens nothing: what follows it is still prose.
    f"Wrap it in `<pre>`.\n\n{FIXES}",
    f"Compare `<pre>` and `<code>`. {FIXES}",
    f"Open a comment with `<!--`.\n\n{FIXES}",
    f"```html\n<pre>\n```\n\n{FIXES}",
    f"> ```html\n> <pre>\n> ```\n\n{FIXES}",
    f"Example `<pre` then {FIXES}",
    f"```\n<pre\n```\n\n{FIXES}",
    # Not a tag at all, so its apostrophe is no unclosed attribute value.
    f"When n <m it's fine. {FIXES}",
)

# One more backticked line than a block's spans are looked for from.
CROWDED = _code_spans._MAX_SPAN_READINGS + 1


def _describes(reference: str) -> bool:
    """Whether a description of `reference` under the attribution names the issue."""
    return _locations.describes_the_issue(
        SimpleNamespace(body=f"{ATTRIBUTION}\n\n{reference}"),
        ISSUE, ATTRIBUTION, SLUG,
    )


class CertainProseTest(unittest.TestCase):
    def test_a_reference_shown_as_code_closes_nothing(self) -> None:
        for shown in (
            *CODE_LINES, *CODE_SPANS, *CODE_IN_HTML, *UNCERTAIN_QUOTING,
            *NO_REFERENCE,
        ):
            with self.subTest(shown=shown):
                self.assertFalse(_describes(shown))

    def test_a_reference_in_prose_closes_the_issue(self) -> None:
        for shown in PROSE:
            with self.subTest(shown=shown):
                self.assertTrue(_describes(shown))

    def test_a_crowded_block_is_code_throughout(self) -> None:
        # The readings a block is given are bounded, so one with more
        # backticked lines than that is not read at all: it is code, which
        # costs a description built that way a line of its own for the reference.
        for lines, closes in ((CROWDED, False), (CROWDED - 1, True)):
            with self.subTest(lines=lines):
                block = "\n".join(("`code`",) * lines)
                self.assertEqual(_describes(f"{block}\n{FIXES}"), closes)


if __name__ == "__main__":
    unittest.main()
