# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Whether a pull request's description closes this issue and names its session."""

from __future__ import annotations

import unittest
from types import SimpleNamespace

from orchestrator.workflow.engine import report_locations as _locations

ISSUE = 12

SLUG = "owner/repository"

OTHER_ISSUE = 13

ATTRIBUTION = "Generated by orchestrator (claude session `sess`)."


class DescribesTheIssueTest(unittest.TestCase):
    def test_every_closing_spelling_github_honours(self) -> None:
        # Bare and repository-qualified references both close this issue --
        # the qualifier compared as GitHub compares it, without case -- while
        # one naming another repository, or another number, closes nothing
        # here. Without the attribution beside it no reference is enough.
        for reference, signed, closes in (
            (f"Fixes #{ISSUE}", ATTRIBUTION, True),
            (f"resolves: Owner/Repository#{ISSUE}", ATTRIBUTION, True),
            (f"Closes someone/else#{ISSUE}", ATTRIBUTION, False),
            (f"Fixes #{OTHER_ISSUE}", ATTRIBUTION, False),
            (f"Fixes #{ISSUE}", "", False),
        ):
            with self.subTest(reference=reference, signed=bool(signed)):
                body = f"{reference}\n\n{signed}"
                self.assertEqual(
                    _locations.describes_the_issue(
                        SimpleNamespace(body=body), ISSUE, ATTRIBUTION, SLUG,
                    ),
                    closes,
                )


if __name__ == "__main__":
    unittest.main()
