# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Which closing references are certainly prose, whichever way Markdown is read.

Held against the closing pattern itself rather than against the text left over,
since what matters is whether a reference GitHub shows as code is ever read as
one that closes the issue. Each case is one way a reading can go wrong: a
container it does not see through, a block it does not see begin, a delimiter
it pairs that Markdown does not.
"""

from __future__ import annotations

import unittest
from types import SimpleNamespace

from orchestrator.workflow.engine import (
    report_locations as _locations,
    report_prose as _prose,
)

ISSUE = 12

SLUG = "owner/repository"

ATTRIBUTION = "Generated by orchestrator (claude session `sess`)."

FIXES = f"Fixes #{ISSUE}"

# Code by the line it stands on: fenced or indented, behind any nesting of list
# and blockquote markers. A fence closes only behind the markers it opened
# behind, so a quoted run inside an unquoted fence closes nothing.
CODE_LINES = (
    f"```\n{FIXES}\n```",
    f"    {FIXES}",
    f">     {FIXES}",
    f"> ~~~\n> {FIXES}\n> ~~~",
    f"> > ```\n> > {FIXES}",
    f"-     {FIXES}",
    f"- -     {FIXES}",
    f"- > ~~~\n  > {FIXES}\n  > ~~~",
    f"> - ~~~\n>   {FIXES}\n>   ~~~",
    f"~~~\n> ~~~\n{FIXES}\n~~~",
)

# Code by the span it stands in. An escaped backtick is a literal character and
# opens nothing, while an escaped BACKSLASH leaves the backtick behind it a real
# opener. Spans pair within one block, and a block can begin with no blank line
# above it -- on a heading, say -- so a span is looked for from every line.
CODE_SPANS = (
    f"Write `{FIXES}` to close it.",
    f"Escaped \\` then `{FIXES}`.",
    f"A backslash \\\\`{FIXES}`",
    f"An unmatched ` here.\n\n`{FIXES}`",
    f"# A ` heading\n`Fixes\n#{ISSUE}`",
    f"`\n*\n{FIXES}`",
    f"foo `\n    ~~~\n    bar\n    ~~~\n{FIXES}`",
)

# Code, or hidden, by the HTML around it; and a keyword parted from its number
# by code, which is no reference however the text around the code reads.
CODE_OTHERWISE = (
    f"<pre>{FIXES}</pre>",
    f"<PRE lang='text'>\n{FIXES}\n</PRE>",
    f"<code>{FIXES}</code>",
    f"<pre>\n{FIXES}",
    f"<!-- {FIXES} -->",
    f"Fixes `a span` #{ISSUE}",
    f"Fixes\n    an indented line\n#{ISSUE}",
)

# The same reference as prose, which a quote or a list item still is. A stray
# backtick pairs with nothing past its own block, an escaped one with nothing at
# all, and inside a span a backslash escapes nothing, so that span ends where it
# says. A fence closed behind its own markers has ended.
PROSE = (
    FIXES,
    f"> {FIXES}",
    f"- {FIXES}",
    f"<details>{FIXES}</details>",
    f"<pre>an example</pre>\n\n{FIXES}",
    f"See `one`. {FIXES}. Also `another`.",
    f"A literal \\` and then {FIXES}, with `code` after.",
    f"`a\\` {FIXES} `b`",
    f"`unclosed {FIXES}",
    f"An unmatched ` here.\n\n{FIXES}",
    f"> ```\n> an example\n> ```\n\n{FIXES}",
)

# One more backticked line than a block's spans are looked for from.
CROWDED = _prose._MAX_SPAN_READINGS + 1


def _describes(reference: str) -> bool:
    """Whether a description of `reference` under the attribution names the issue."""
    return _locations.describes_the_issue(
        SimpleNamespace(body=f"{ATTRIBUTION}\n\n{reference}"),
        ISSUE, ATTRIBUTION, SLUG,
    )


class CertainProseTest(unittest.TestCase):
    def test_a_reference_shown_as_code_closes_nothing(self) -> None:
        for shown in (*CODE_LINES, *CODE_SPANS, *CODE_OTHERWISE):
            with self.subTest(shown=shown):
                self.assertFalse(_describes(shown))

    def test_a_reference_in_prose_closes_the_issue(self) -> None:
        for shown in PROSE:
            with self.subTest(shown=shown):
                self.assertTrue(_describes(shown))

    def test_a_crowded_block_is_code_throughout(self) -> None:
        # The readings a block is given are bounded, so one with more
        # backticked lines than that is not read at all: it is code, which
        # costs a description built that way a line of its own for the reference.
        for lines, closes in ((CROWDED, False), (CROWDED - 1, True)):
            with self.subTest(lines=lines):
                block = "\n".join(("`code`",) * lines)
                self.assertEqual(_describes(f"{block}\n{FIXES}"), closes)


if __name__ == "__main__":
    unittest.main()
