# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Which closing references are certainly prose, whichever way Markdown is read.

Held against the closing pattern itself rather than against the text left over,
since what matters is whether a reference GitHub shows as code is ever read as
one that closes the issue. Each case is one way a reading can go wrong: a
container it does not see through, a block it does not see begin, a delimiter
it pairs that Markdown does not.
"""

from __future__ import annotations

import re
import unittest
from types import SimpleNamespace
from unittest.mock import patch

from orchestrator.workflow.engine import (
    report_code_spans as _code_spans,
    report_html_literals as _html,
    report_link_fields as _link_fields,
    report_locations as _locations,
)

ISSUE = 12

SLUG = "owner/repository"

ATTRIBUTION = "Generated by orchestrator (claude session `sess`)."

FIXES = f"Fixes #{ISSUE}"

# Whitespace to Python's `\s` and none to HTML, whose own is five ASCII
# characters: each is a character of whatever tag name it stands in.
NO_HTML_SPACE = ("\N{NO-BREAK SPACE}", "\x0b", "\N{LINE SEPARATOR}")

# Code by the line it stands on: fenced or indented, behind any nesting of list
# and blockquote markers. A fence closes only behind the markers it opened
# behind, so a quoted run inside an unquoted fence closes nothing.
CODE_LINES = (
    f"```\n{FIXES}\n```",
    f"    {FIXES}",
    f">     {FIXES}",
    f"> ~~~\n> {FIXES}\n> ~~~",
    f"> > ```\n> > {FIXES}",
    f"-     {FIXES}",
    f"- -     {FIXES}",
    f"- > ~~~\n  > {FIXES}\n  > ~~~",
    f"> - ~~~\n>   {FIXES}\n>   ~~~",
    f"~~~\n> ~~~\n{FIXES}\n~~~",
    # Markdown ends a line on a bare carriage return too, and on the pair.
    f"Intro\r\r    {FIXES}",
    f"Intro\r\n\r\n    {FIXES}",
    f"~~~\r{FIXES}\r~~~",
)

# Code by the span it stands in. An escaped backtick is a literal character and
# opens nothing, while an escaped BACKSLASH leaves the backtick behind it a real
# opener. Spans pair within one block, and a block can begin with no blank line
# above it -- on a heading, say -- so a span is looked for from every line.
CODE_SPANS = (
    f"Write `{FIXES}` to close it.",
    f"Escaped \\` then `{FIXES}`.",
    f"A backslash \\\\`{FIXES}`",
    f"An unmatched ` here.\n\n`{FIXES}`",
    f"# A ` heading\n`Fixes\n#{ISSUE}`",
    f"`\n*\n{FIXES}`",
    f"foo `\n    ~~~\n    bar\n    ~~~\n{FIXES}`",
    # Pairing starts afresh wherever a stretch of inline text does: in each cell
    # of a table, and past a tag or an autolink that took a backtick for its own.
    f"| Field | Value |\n| --- | --- |\n| stray ` | `{FIXES}` |",
    f"Field | Value\n:-- | --:\nstray ` | `{FIXES}`",
    f'see <a title="`">a link</a> `{FIXES}`',
    f"<http://example.com/`x> `{FIXES}`",
    # So does a bare URL, which GitHub links where it stands: by scheme or by
    # `www.`, in any case, through every backtick to the whitespace GitHub ends
    # one on -- which a no-break space is not.
    f"https://example.com/`x `{FIXES}`",
    f"www.example.com/`x `{FIXES}`",
    f"see HTTP://example.com/`x and `{FIXES}`",
    f"ftp://example.com/`x `{FIXES}`",
    f"https://example.com/`x\N{NO-BREAK SPACE}`y `{FIXES}`",
    # A link or an image reads its destination and title itself once its text
    # has closed, and a reference its label: a backtick there pairs with nothing.
    f'[link](https://example.com "`") `{FIXES}`',
    f'![image](https://example.com/a.png "`") `{FIXES}`',
    f"[link](<https://example.com/`>) `{FIXES}`",
    f"[text][la`bel] `{FIXES}`",
    f"$a ` b$ `{FIXES}`",
)

# Code, or hidden, by the HTML around it, read off the text as written: an
# element is literal whether or not some reading pairs a backtick across its
# opening tag. Nested tags are counted, a stray closing tag closes nothing, and
# neither does one a code span or a comment may hide.
CODE_IN_HTML = (
    f"<pre>{FIXES}</pre>",
    f"<PRE lang='text'>\n{FIXES}\n</PRE>",
    f"<code>{FIXES}</code>",
    f"<pre>\n{FIXES}",
    f"<!-- {FIXES} -->",
    f"`unmatched\n<pre>` {FIXES}</pre>",
    f"<code><code>example</code> {FIXES}</code>",
    f"<pre><code>example</code> {FIXES}</pre>",
    f"<pre></code> {FIXES}</pre>",
    f"text <pre>`</pre> `{FIXES}`",
    f"<pre><!-- </pre> --> {FIXES}</pre>",
    f"<textarea>{FIXES}</textarea>",
    f"<pre {FIXES}",
    # A tag is read as HTML reads one: a `>` or a closing tag inside a quoted
    # attribute value ends nothing, and a value never closed takes the rest.
    f'<pre data-example="> </pre>">{FIXES}</pre>',
    f"<pre data-example='> </pre>'>{FIXES}</pre>",
    f'<pre data-example="x> </pre> {FIXES}',
    # EVERY tag is read, so a closing tag inside another tag's value closes
    # nothing -- a value being what follows a name's `=`, and a stray quote
    # anywhere else a character like any other. Nor does one inside the bogus
    # comment a `<!` opens.
    f'<code><a title="</code>">{FIXES}</a></code>',
    f'<pre><a title="</pre>">{FIXES}</a></pre>',
    f"<pre><a title='</pre>'>{FIXES}</a></pre>",
    f'<pre><a x" y="> </pre>">{FIXES}</a></pre>',
    f'<pre><a =" d="> </pre>">{FIXES}</a></pre>',
    f"<pre><!x </pre {FIXES}</pre>",
    # An opening tag counts wherever it is found, since what shelters it may
    # be no tag, and no comment, as Markdown reads it.
    f'<a title="<pre>"> {FIXES}',
    f"see <!-- a -- <pre> --> {FIXES}",
    # A name is read to HTML's whitespace and folded in ASCII alone, so neither
    # of these closing tags names the element it stands in.
    *(f"<pre>Literal </pre{space}> {FIXES}</pre>" for space in NO_HTML_SPACE),
    f"<kbd>Literal </\N{KELVIN SIGN}bd> {FIXES}</kbd>",
    # A name runs on through a `<`, so the opening tag right behind one is
    # looked for inside it; and an element opened in a tag's markup is literal
    # from where that markup began, the attributes before it included.
    f"<x<code>{FIXES}</code>",
    f"<a <b<code>{FIXES}</code>",
    f'see <a title="{FIXES} <pre>"> the link',
)

# What GitHub renders as nothing: a declaration, a processing instruction, a
# CDATA section, and the bogus comment any other `<!`, `<?` or `</` opens. Each
# to the later of Markdown's terminator and HTML's `>`, or to the end of a text
# with neither; and read on as HTML from that `>`, where a comment may open that
# Markdown's terminator does not close.
HIDDEN = (
    f"<!DOCTYPE html {FIXES}>",
    f"<?{FIXES}?>",
    f"<![CDATA[{FIXES}]]>",
    f"<?php a > {FIXES} ?>",
    f"<![CDATA[ a > {FIXES} ]]>",
    f"<?php {FIXES}",
    f"<!x {FIXES}",
    f"<div>\n</ {FIXES}>\n</div>",
    f"<![CDATA[ > <!-- ]]> {FIXES}",
    f"<?php > <pre> ?> {FIXES}",
    # Whatever was taken out opens a line as a marker does, since it may have
    # opened an HTML block: a tag behind it that nothing closes takes the rest.
    f'<!-- a note --> <div title="{FIXES}',
)

# What Markdown itself reads and shows nothing of: a link reference definition
# -- its label, its destination, and a title on its line or the lines below,
# behind whatever markers its line opens on -- and, behind a link's or an
# image's text, the destination and the title, or the label of the definition it
# names. An image's description is an attribute once rendered.
# Deeper in parentheses than a destination is read pair by pair, and a
# destination that deep with every pair closed.
DEEPER = 40

DEEP_DESTINATION = "x".join(("(" * DEEPER, ")" * DEEPER))

UNSHOWN = (
    f"[{FIXES}]: https://example.com",
    f'[docs]: https://example.com "{FIXES}"',
    f"[docs]: https://example.com\n  '{FIXES}'",
    f'[docs]:\n  https://example.com\n  "a title\n{FIXES}"',
    f"> [docs]: <https://example.com> ({FIXES})",
    f'- [docs]: https://example.com "{FIXES}"',
    f'[link](https://example.com "{FIXES}")',
    f"[link](https://example.com '{FIXES}')",
    f"[link](https://example.com ({FIXES}))",
    f'[link](https://example.com "a \\" {FIXES}")',
    f'[link](https://example.com/a_(b) "{FIXES}")',
    f"[link](<{FIXES}>)",
    f"[link](fixes:#{ISSUE})",
    f"[text][{FIXES}]",
    f'![image](https://example.com/a.png "{FIXES}")',
    f"![{FIXES}](https://example.com/a.png)",
    # A destination holds parentheses in pairs however deep, and a description
    # brackets, a link or another image; an escaped bracket closes nothing, and
    # neither does one in a tag's attribute.
    f'[link](https://example.com/a_(b_(c)) "{FIXES}")',
    f'[link]({DEEP_DESTINATION} "{FIXES}")',
    f"![nested [label] {FIXES}](https://example.com/a.png)",
    f"![a ![b](c) {FIXES}](https://example.com/a.png)",
    f"![a \\] {FIXES}](https://example.com/a.png)",
    f'![a <b title="]"> {FIXES}](https://example.com/a.png)',
    # An image is one by a definition elsewhere too, collapsed or shortcut or
    # by another label, and nobody looks the definition up.
    f"![{FIXES}][]\n\n[{FIXES}]: https://example.com/a.png",
    f"![{FIXES}]\n\n[{FIXES}]: https://example.com/a.png",
    f"![{FIXES}][image]\n\n[image]: https://example.com/a.png",
    f"![{FIXES}]",
    # A title goes on over a line ending, one behind a backslash included --
    # which escapes nothing there, and ends no title -- and so does a label.
    # Nor does a backslash escape the whitespace that ends a destination.
    f'[link](url "first\\\n{FIXES}")',
    f"[link](url 'first\\\n{FIXES}')",
    f"[link](url (first\\\n{FIXES}))",
    f'![image](url "first\\\n{FIXES}")',
    f'[docs]: url "first\\\n{FIXES}"',
    f"[docs]: url\n  'first\\\n{FIXES}'",
    f"[{FIXES}\\\nmore]: url",
    f'[link](a\\ "{FIXES}")',
    # The parts of a link stand either side of a line ending behind the
    # blockquote markers the next line opens on, which Markdown has off first.
    f'> [docs]: url\n> "{FIXES}"',
    f'> [docs]:\n> url\n> "{FIXES}"',
    f'> [link](url\n> "{FIXES}")',
    f'> > [link](\n> > url\n> > "{FIXES}"\n> > )',
    # Which backticks pair is a doubt of a link's and a tag's too. A span only
    # SOME reading encloses -- from a backtick a bare URL or math took, into a
    # title, a description or an attribute -- takes the syntax around it along,
    # so what is not shown is read with such a span still in the text as well.
    f'https://example.com/`x [link](url "a ` {FIXES}")',
    f'www.example.com/`x [link](url\n"a ` {FIXES}")',
    f"https://example.com/`x ![a ` {FIXES}](url)",
    f'https://example.com/`x <a title="a ` {FIXES}">link</a>',
    f'$a ` b$ [link](url "a ` {FIXES}")',
)

# A tag quoted as code is no tag only where the code is CERTAIN. Not after a
# `<` that may have taken the backtick into a tag of its own; not in a fence an
# HTML block may hold, one Markdown closes sooner than the strict reading, or a
# quoted one a blank line ended; and never inside an element already open.
UNCERTAIN_QUOTING = (
    f'see <a title="`"><pre>` {FIXES}',
    f"<div>\n```\n<pre>\n```\n</div>\n\n{FIXES}",
    f"~~~\nx\n ~~~\n<pre>\n~~~\n{FIXES}",
    f"> ```\n\n> <pre>\n> ```\n> {FIXES}",
    f"<pre>\n\n`<pre>` x</pre> {FIXES}</pre>",
    f"| ` | <pre> ` {FIXES} |\n| --- | --- |",
    f'[link](https://example.com "`") <pre> ` {FIXES}',
    # A quoted tag is passed over at its name, never read on to a `>` of its
    # own: cut short inside its code, it would take the real tag after that
    # code as its attributes, and hide the element that opens.
    f"Example `<pre` then <code>{FIXES}</code>",
    f"Example `</pre` then <pre>{FIXES}</pre>",
    f"Example `<!--` then <code>{FIXES}</code>",
    f"```\n<pre\n```\n\n<code>{FIXES}</code>",
    # Nor at its name, which runs on through the backtick that ends its code
    # and into the tag behind it.
    f"`<x`<code>{FIXES}</code>",
    f"`<x<y`<code>{FIXES}</code>",
    f"`<?`<code>{FIXES}</code>",
)

# No reference at all, however the text around it reads: a keyword parted from
# its number by code, and one inside a tag's own markup.
NO_REFERENCE = (
    f"Fixes `a span` #{ISSUE}",
    f"Fixes\n    an indented line\n#{ISSUE}",
    f'<a title="{FIXES}">a link</a>',
    f'<a title="> {FIXES}">a link</a>',
    f'<a x" y="> {FIXES} ">a link</a>',
    f'<a title\N{NO-BREAK SPACE}="> {FIXES} ">a link</a>',
    f'<div title="{FIXES}',
)

# The same reference as prose, which a quote or a list item still is. A stray
# backtick pairs with nothing past its own block, an escaped one with nothing at
# all, and inside a span a backslash escapes nothing, so that span ends where it
# says. A fence closed behind its own markers has ended.
PROSE = (
    FIXES,
    f"> {FIXES}",
    f"- {FIXES}",
    f"<details>{FIXES}</details>",
    f"<pre>an example</pre>\n\n{FIXES}",
    f"See `one`. {FIXES}. Also `another`.",
    f"A literal \\` and then {FIXES}, with `code` after.",
    f"`a\\` {FIXES} `b`",
    f"`unclosed {FIXES}",
    f"An unmatched ` here.\n\n{FIXES}",
    f"> ```\n> an example\n> ```\n\n{FIXES}",
    f"```html\n<pre>\nan example\n</pre>\n```\n\n{FIXES}",
    f"<!-- a note --> {FIXES}",
    f"{FIXES}\n\nWrap it in `<pre>`.",
    f"Intro\r\r{FIXES}",
    # A tag quoted as an example, in a span or a closed fence that is code
    # however the text is read, opens nothing: what follows it is still prose.
    f"Wrap it in `<pre>`.\n\n{FIXES}",
    f"Compare `<pre>` and `<code>`. {FIXES}",
    f"Open a comment with `<!--`.\n\n{FIXES}",
    f"```html\n<pre>\n```\n\n{FIXES}",
    f"> ```html\n> <pre>\n> ```\n\n{FIXES}",
    f"Example `<pre` then {FIXES}",
    f'Example `<a title="` then <code>x</code> {FIXES}',
    f'<a href="https://example.com">a link</a> {FIXES}',
    f"<details><summary>More</summary>{FIXES}</details>",
    # HTML's own whitespace ends a name, in either case of it; a no-break
    # space makes `pre` another element's name, which shows nothing literally.
    f"<pre>Literal</pre\t> {FIXES}",
    f"<pre>Literal</PRE\x0c> {FIXES}",
    f"<pre\N{NO-BREAK SPACE}>Shown as prose</pre> {FIXES}",
    # A pipe is a cell's edge only where a table may be, and a `>` ends a tag
    # only where a `<` has begun one: a shell pipe in a span and a comparison
    # in prose leave the pairing as it was.
    f"Run `a | b` then `c`. {FIXES} via `d`.",
    f"Where a > b use `x`. {FIXES} as `y` does.",
    # Nor does a link, a task box or a price, where the backticks past it pair.
    f"[The docs](https://example.com) mention `a`. {FIXES} with `b`.",
    f"See https://example.com/docs for `a`. {FIXES} with `b`.",
    # What is not shown has ended: a link's or an image's destination and
    # title, a definition on lines of its own, and the label a link names.
    # Brackets and parentheses that are no link hide nothing.
    f"[The docs](https://example.com) say so. {FIXES}",
    f'![image](https://example.com/a.png "a title") {FIXES}',
    f'[1]: https://example.com "docs"\n[2]: https://example.org\n\n{FIXES}',
    f"See [the docs][1]. {FIXES}\n\n[1]: https://example.com",
    f"[see](the docs) {FIXES}",
    f"A list [a, b] and f(x) here. {FIXES}",
    f"- [x] done (mostly). {FIXES}",
    f"![an image](https://example.com/a.png) {FIXES}",
    f"![an image][] {FIXES}\n\n[an image]: https://example.com/a.png",
    f"![unclosed {FIXES}",
    f'[link](url "a title\\\nin two lines") {FIXES}',
    f'[link](url "first\\\\" {FIXES} "x")',
    f"> [docs]: url\n> {FIXES}",
    # Read with possible code still in the text, a link or a tag hides what is
    # its own and no more; one quoted in certain code is never read at all, and
    # a tag nothing closes takes no rest of a text its line may be code in.
    f'https://example.com/`x [link](url "a ` title") {FIXES}',
    f'Write `[a](url "` then {FIXES} ")',
    f'Write `<a title="` then {FIXES} ">',
    f"See `![` and later ] {FIXES}",
    f"    <T extends Comparable\n\n{FIXES}",
    f"> [link](url)\n> {FIXES}",
    f"Done! [The docs](https://example.com) say so. {FIXES}",
    f"- [x] done with `a`. {FIXES} and `b`",
    f"It costs $5 for `a`. {FIXES} and `b`",
    f"`a[0]` and `f(x)` stay code. {FIXES} as `b` does.",
    f"| Field | Value |\n| --- | --- |\n| `code` | {FIXES} |",
    f"| a | b |\n| --- | --- |\n| `x` | `y` |\n\n{FIXES}",
    f"```\n<pre\n```\n\n{FIXES}",
    # Not a tag at all, so its apostrophe is no unclosed attribute value.
    f"When n <m it's fine. {FIXES}",
    # What is hidden has ended, by either reading of it; quoted as code it
    # never began.
    f"<?php a ?> {FIXES}",
    f"<!DOCTYPE html> {FIXES}",
    f"<![CDATA[x]]> {FIXES}",
    f"<?php a > {FIXES}",
    f"Use the </> icon. {FIXES}",
    f"Open one with `<?php` or `<![CDATA[`.\n\n{FIXES}",
    # A name is read whole, as HTML reads one: a quote inside it opens no value.
    f'- <ab="> then {FIXES}',
)

# As long as GitHub lets a description be, and nothing but openers: tags that
# nothing closes, their names run together or apart, or behind an attribute
# value that never closes.
LONGEST = 65536

OPENERS = ("<a", "<a ", '<a b="x" c="', "`<a")

# And nothing but links whose destinations open more parentheses than any closes.
DEEP_DESTINATIONS = ("[a](x(", "[](".ljust(DEEPER, "("))

# One more backticked line than a block's spans are looked for from.
CROWDED = _code_spans._MAX_SPAN_READINGS + 1


def _describes(reference: str) -> bool:
    """Whether a description of `reference` under the attribution names the issue."""
    return _locations.describes_the_issue(
        SimpleNamespace(body=f"{ATTRIBUTION}\n\n{reference}"),
        ISSUE, ATTRIBUTION, SLUG,
    )


class _Budgeted:
    """A pattern of the readers', asked no more than `budget` times."""

    def __init__(self, pattern: re.Pattern[str], budget: int) -> None:
        self._left = budget
        self._pattern = pattern

    def match(self, text: str, position: int) -> object:
        self._spend()
        return self._pattern.match(text, position)

    def search(self, text: str, position: int) -> object:
        self._spend()
        return self._pattern.search(text, position)

    def _spend(self) -> None:
        self._left -= 1
        if self._left < 0:
            raise AssertionError("the text was read more often than it allows")


class CertainProseTest(unittest.TestCase):
    def test_a_reference_shown_as_code_closes_nothing(self) -> None:
        for shown in (
            *CODE_LINES, *CODE_SPANS, *CODE_IN_HTML, *HIDDEN, *UNSHOWN,
            *UNCERTAIN_QUOTING, *NO_REFERENCE,
        ):
            with self.subTest(shown=shown):
                self.assertFalse(_describes(shown))

    def test_a_reference_in_prose_closes_the_issue(self) -> None:
        for shown in PROSE:
            with self.subTest(shown=shown):
                self.assertTrue(_describes(shown))

    def test_a_text_of_openers_is_read_once(self) -> None:
        # Every tag nothing closes is read to the end of the text, so what one
        # reading found is remembered: the attributes read stay in proportion
        # to the text, where reading each opener afresh squares them.
        for opener in OPENERS:
            with self.subTest(opener=opener):
                openers = opener * (LONGEST // len(opener))
                budgeted = _Budgeted(_html._ATTRIBUTE_RE, 2 * LONGEST)
                with patch.object(_html, "_ATTRIBUTE_RE", budgeted):
                    self.assertTrue(_describes(f"{FIXES} {openers}"))

    def test_a_text_of_deep_destinations_is_read_once(self) -> None:
        # A destination deeper in parentheses than is read pair by pair runs to
        # the whitespace that ends it, which is looked for once for the run
        # they all stand in rather than once from each.
        for opener in DEEP_DESTINATIONS:
            with self.subTest(opener=opener):
                openers = opener * (LONGEST // len(opener))
                budgeted = _Budgeted(_link_fields._DESTINATION_END_RE, 2)
                with patch.object(_link_fields, "_DESTINATION_END_RE", budgeted):
                    self.assertTrue(_describes(f"{FIXES} {openers}"))

    def test_a_crowded_block_is_code_throughout(self) -> None:
        # The readings a block is given are bounded, so one with more
        # backticked lines than that is not read at all: it is code, which
        # costs a description built that way a line of its own for the reference.
        for lines, closes in ((CROWDED, False), (CROWDED - 1, True)):
            with self.subTest(lines=lines):
                block = "\n".join(("`code`",) * lines)
                self.assertEqual(_describes(f"{block}\n{FIXES}"), closes)


if __name__ == "__main__":
    unittest.main()
