# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""The two clients the append-only evidence contracts are held against.

A developer report and a workflow verification artifact are published onto one
conversation the same way, so one pair of backends answers for both. The real
client is driven over pull requests shaped the way PyGithub hands them over, so
the requests it makes are the ones production makes; the shared fake is driven
over its own records. Each backend can fail a read, refuse a post, or land a
post and lose its response, and each reports what was written to the
description, which neither kind of evidence may ever touch.
"""
from __future__ import annotations

from collections.abc import Iterator
from functools import partial
from itertools import count
from unittest.mock import MagicMock

from github import GithubException

from orchestrator.github.client import GitHubClient
from tests.support.fakes import FakeComment, FakeGitHubClient, FakePR, FakeUser

BOT_LOGIN = "orchestrator"
PR_NUMBER = 12
OTHER_PR_NUMBER = 13

# A description holding everything a report-driven rewrite would put at risk:
# the closing reference, the attribution line, a legacy agent-message heading,
# and a maintainer's sentence under it that nothing marks as theirs.
LEGACY_BODY = (
    "Resolves #7\n\n"
    "Generated by orchestrator (codex session `s-1`).\n\n"
    "---\n_Last agent message:_\n\n"
    "> implemented\n\n"
    "A sentence a maintainer added afterwards."
)

# How a backend leaves a request unanswered.
UNREADABLE = "unreadable"
REFUSED = "refused"
LOST = "lost"

_FIRST_WIRE_ID = 5000
_HTTP_UNPROCESSABLE = 422
_HTTP_BAD_GATEWAY = 502


def wire_pull_request(number: int, body: str, ids: Iterator[int]) -> MagicMock:
    """A pull request the way PyGithub hands one over, recording every write.

    Its requests keep PyGithub's own names -- the thread read, the comment
    post, and the description edit a report must never make -- and answer from
    `issue_comments`, which a case seeds and inspects directly. `failing` names
    how the requests go unanswered, or is None.
    """
    pull_request = MagicMock(
        number=number, body=body, issue_comments=[], failing=None,
    )
    pull_request.get_issue_comments.side_effect = partial(_read_thread, pull_request)
    pull_request.create_issue_comment.side_effect = partial(
        _post_comment, pull_request, ids,
    )
    return pull_request


def _read_thread(pull_request: MagicMock) -> list[FakeComment]:
    if pull_request.failing == UNREADABLE:
        raise GithubException(_HTTP_BAD_GATEWAY, {}, None)
    return list(pull_request.issue_comments)


def _post_comment(
    pull_request: MagicMock, ids: Iterator[int], body: str,
) -> FakeComment:
    if pull_request.failing == REFUSED:
        raise GithubException(_HTTP_UNPROCESSABLE, {}, None)
    posted = FakeComment(
        id=next(ids),
        body=body,
        user=FakeUser(BOT_LOGIN),
    )
    pull_request.issue_comments.append(posted)
    if pull_request.failing == LOST:
        raise ConnectionError("the response to the post never arrived")
    return posted


class WireBackend:
    """The real client, over pull requests shaped the way PyGithub hands them over."""

    def setUp(self) -> None:
        self._ids = count(_FIRST_WIRE_ID)
        self.pull_request = wire_pull_request(PR_NUMBER, LEGACY_BODY, self._ids)
        self._pulls = {
            PR_NUMBER: self.pull_request,
            OTHER_PR_NUMBER: wire_pull_request(OTHER_PR_NUMBER, "", self._ids),
        }
        # Bypass the networked __init__: the report requests read only the
        # repository and the login the client authenticated as.
        self.gh = GitHubClient.__new__(GitHubClient)
        self.gh._bot_login = BOT_LOGIN
        self.gh.repo = MagicMock()
        self.gh.repo.get_pull.side_effect = self._get_pull

    def refuse(self, failure: str | None) -> None:
        """Leave the pull request's requests unanswered one way, or answer them again."""
        self.pull_request.failing = failure

    def seed(self, body: str, *, login: str) -> FakeComment:
        seeded = FakeComment(
            id=next(self._ids),
            body=body,
            user=FakeUser(login),
        )
        self.pull_request.issue_comments.append(seeded)
        return seeded

    def description_writes(self) -> list:
        return self.pull_request.edit.call_args_list

    def posted_comments(self) -> list:
        """Every comment this client posted, read off the requests it made."""
        return [
            (PR_NUMBER, posted.args[0])
            for posted in self.pull_request.create_issue_comment.call_args_list
        ]

    def _get_pull(self, pr_number: int) -> MagicMock:
        pull_request = self._pulls.get(pr_number)
        if pull_request is None or pull_request.failing == UNREADABLE:
            raise GithubException(_HTTP_BAD_GATEWAY, {}, None)
        return pull_request


class FakeBackend:
    """The shared in-memory client, over its own pull-request records."""

    def setUp(self) -> None:
        self.gh = FakeGitHubClient(bot_login=BOT_LOGIN)
        self.pull_request = FakePR(number=PR_NUMBER, body=LEGACY_BODY)
        self.gh.add_pr(self.pull_request)
        self.gh.add_pr(FakePR(number=OTHER_PR_NUMBER))

    def refuse(self, failure: str | None) -> None:
        """Leave the pull request's requests unanswered one way, or answer them again."""
        failures = self.gh.report_failures
        named = {
            UNREADABLE: failures.unreadable,
            REFUSED: failures.refused,
            LOST: failures.lost,
        }
        for pr_numbers in named.values():
            pr_numbers.discard(PR_NUMBER)
        if failure is not None:
            named[failure].add(PR_NUMBER)

    def seed(self, body: str, *, login: str) -> FakeComment:
        seeded = FakeComment(
            id=self.gh.next_reply_id(self.pull_request),
            body=body,
            user=FakeUser(login),
        )
        self.pull_request.issue_comments.append(seeded)
        return seeded

    def description_writes(self) -> list:
        return self.gh.edited_pr_bodies

    def posted_comments(self) -> list:
        """Every comment this client posted, read off the ledger it keeps of ours."""
        return list(self.gh.posted_pr_comments)
