# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""What a developer's report leaves behind, for the fixtures that publish work.

The implementing stage holds a finished run to the report contract and hands
work on only under a description that names it, so every fixture whose run
finishes, whose worktree already carries commits, or whose branch already has a
pull request says so the way production does.
"""
from __future__ import annotations

from orchestrator import config
from orchestrator.workflow.engine import content_hash as _content_hash

# What a finished developer run's message ends on. Every developer prompt
# teaches the report contract, and the implementing stage holds a completed run
# to it: work published with no report reaches review with nothing describing
# it and no session left to ask, so a fixture whose run FINISHES says so the
# way a developer does.
_FINISHED_REPORT = (
    "REPORT: READY\nThe branch does what the issue asked, verified by the "
    "suite.\nREPORT: END"
)


def _reported(message: str = "implemented") -> str:
    """One finished run's last message: what it said, then its report."""
    return f"{message}\n\n{_FINISHED_REPORT}"


def _recovered_report(issue) -> dict:
    """The pinned record a run that committed, and died, left behind.

    What every tick whose worktree ALREADY carries commits is seeded with,
    because that is what one looks like in production: the run that made those
    commits recorded its report before the size gate and before the push, so
    an issue reaching a later tick with committed work carries the report of
    the run that committed it. A tick finding commits and no record at all is
    the window that recording exists to close -- a lost pinned write -- and
    the stage holds it for a human rather than publishing it undescribed.

    The requirements revision is the issue's own content hash, since the run
    this stands in for was handed exactly the issue in hand: one naming an
    older revision is an edit landing mid-run, which is a different road.
    """
    return {
        "developer_report_delivery": {
            "receipt": f"issue-{issue.number}-report-1",
            "revision": 1,
            "requirements": _content_hash._compute_user_content_hash(issue, ()),
            "mode": "publish",
            "route": "workflow:implementing",
            "watermarks": [],
            "spends": [],
            "report": "the run that made this commit reported it.",
        },
    }


def _named_description(
    issue_number: int, session_id: str = "sess-1", backend: str = "",
) -> str:
    """The description this stage writes on a pull request it opens.

    Its closing reference and the developer's attribution, which is what a
    reused pull request of this issue's own carries -- and so the one a
    publication adopts as it stands, where any other is held for a human.
    `backend` is the pinned `dev_agent`, or the configured one where none is.
    """
    agent = backend or config.DEV_AGENT
    return (
        f"Resolves #{issue_number}\n\n"
        f"Generated by orchestrator ({agent} session `{session_id}`)."
    )
