# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""What a reused pull request's description keeps, and when it holds the work.

The description is judged as it stands NOW, read afresh, and a body that does
not name this implementation gets the two lines above it with every word kept.
`test_report_publication` covers the bodies left alone because of what they SAY.
"""

from __future__ import annotations

import copy
import unittest
from types import MappingProxyType
from unittest.mock import patch

from orchestrator import config
from orchestrator.github import developer_reports as _reports
from orchestrator.github.pinned_state import MAX_PINNED_BODY, PinnedState
from orchestrator.github.pull_request_reports import ReportLocation
from orchestrator.workflow.engine import (
    report_delivery as _report_delivery,
    report_records as _records,
    report_settlement_state as _settlement,
)
from tests.workflow.fixtures import (
    _TEST_SPEC,
    LABEL_VALIDATING,
    SHA_LENGTH,
    _open_pr_for,
)
from tests.workflow.stages.implementing import report_test_support as support

REUSED_PR = 71

# What a human wrote over the body: no closing reference, no attribution.
HUMAN_DESCRIPTION = "### Notes\n\nRewritten by hand, and meant to stay."

# What the body said when the lookup fetched it, before that edit landed.
LOOKED_UP_DESCRIPTION = "### Plan\n\nThe description the lookup fetched."

# What this stage wrote on a pull request it opened: the closing reference and
# the session, which is everything a reuse leaves alone.
OWN_DESCRIPTION = (
    f"Resolves #{support.REPORT_ISSUE}\n\n"
    f"Generated by orchestrator ({config.DEV_AGENT} session "
    f"`{support.DEV_SESSION}`)."
)

EARLIER_HEADING = "_Description before this implementation:_"

GET_PR = "get_pr"

AWAITING_HUMAN = "awaiting_human"

PARK_REASON = "park_reason"

# A commit an earlier publication of this issue's settled its report about.
EARLIER_SHA = "e" * SHA_LENGTH

# A description a few characters under GitHub's ceiling, which the two lines
# this implementation needs above it would take past that ceiling.
NEAR_THE_CEILING = "x" * (MAX_PINNED_BODY - 10)

# What the notice for that description says, and no other notice does.
TOO_LONG_NOTICE = "too long to have this issue's closing reference"

# A record whose location still names the reused pull request's description
# while the rest of it will not read.
DAMAGED_RECORD = MappingProxyType({
    "location_pr": REUSED_PR,
    "location_comment": None,
    "revision": "damaged",
})


class _ReusedPullRequest(support._ReportDeliveryMixin):
    """A human's pull request already open on the branch this issue pushes."""

    def _reused_over(self, **pinned):
        """An issue carrying `pinned`, with a human's pull request on its branch."""
        github, issue = self.seeded()
        github.seed_state(support.REPORT_ISSUE, **pinned)
        reused = _open_pr_for(
            github, issue_number=support.REPORT_ISSUE, pr_number=REUSED_PR,
        )
        reused.body = HUMAN_DESCRIPTION
        github.existing_open_pr[support.BRANCH] = reused
        return github, issue, reused

    def _edited_after_the_lookup(self, fetched: str):
        """A reused pull request a human edited after the lookup fetched it.

        The lookup's object is a copy holding the body it was fetched with,
        which is what a pull request GitHub handed back is: a snapshot.
        """
        github, issue, live = self._reused_over()
        looked_up = copy.copy(live)
        looked_up.body = fetched
        github.existing_open_pr[support.BRANCH] = looked_up
        return github, issue


class DescriptionGuardTest(unittest.TestCase, _ReusedPullRequest):
    def test_an_edit_after_the_lookup_is_kept(self) -> None:
        # A human replaced the body after the lookup fetched it -- a plan's, or
        # this stage's own complete one. Judged afresh, what they wrote stays
        # beneath this implementation's lines instead of being overwritten or
        # handed to review closing nothing.
        for looked_up in (LOOKED_UP_DESCRIPTION, OWN_DESCRIPTION):
            with self.subTest(looked_up=looked_up):
                github, issue = self._edited_after_the_lookup(looked_up)

                self.deliver(github, issue, support.ready_message())

                self.assertEqual(len(github.edited_pr_bodies), 1)
                named, earlier = github.edited_pr_bodies[0][1].split(
                    EARLIER_HEADING,
                )
                self.assertEqual(
                    (
                        named.startswith(f"Resolves #{support.REPORT_ISSUE}"),
                        support.DEV_SESSION in named,
                        earlier.strip(),
                        len(support.published_reports(github, REUSED_PR)),
                    ),
                    (True, True, HUMAN_DESCRIPTION, 1),
                )
                self.assertIn(
                    (support.REPORT_ISSUE, LABEL_VALIDATING),
                    github.label_history,
                )

    def test_an_unreadable_description_holds(self) -> None:
        # Nothing is written over a description nobody could read, and nothing
        # is handed on: the commit stays owed for the next tick.
        github, issue, reused = self._reused_over()

        with patch.object(github, GET_PR, _Unreadable(REUSED_PR, github.get_pr)):
            self.deliver(github, issue, support.ready_message())

        self.assertEqual(
            (github.edited_pr_bodies, reused.body), ([], HUMAN_DESCRIPTION),
        )
        self.assertEqual(support.published_reports(github, REUSED_PR), [])
        self.assertNotIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_damaged_record_keeps_the_description(self) -> None:
        # A damaged record may still name the description, so the body stays,
        # the record stays, and the work is not handed on.
        for record, run in (
            (support.DELIVERY_RECORD, self.republish),
            (support.CURRENT_RECORD, self._delivers),
        ):
            with self.subTest(record=record):
                github, issue, reused = self._reused_over(
                    dev_session_id=support.DEV_SESSION,
                    **{record: dict(DAMAGED_RECORD)},
                )

                run(github, issue)

                self.assertEqual(
                    (
                        github.edited_pr_bodies,
                        reused.body,
                        github.pinned_data(support.REPORT_ISSUE)[record],
                    ),
                    ([], HUMAN_DESCRIPTION, dict(DAMAGED_RECORD)),
                )
                self.assertNotIn(
                    (support.REPORT_ISSUE, LABEL_VALIDATING),
                    github.label_history,
                )

    def _delivers(self, github, issue):
        """Run the ordinary tick, whose developer reports for publication."""
        return self.deliver(github, issue, support.ready_message())


class DescriptionHoldTest(unittest.TestCase, _ReusedPullRequest):
    """The descriptions a publication may not be handed on under."""

    def test_a_stale_lookup_hides_no_collision(self) -> None:
        # The report was verified on the description as it stands -- closing
        # nothing, naming nobody -- while the lookup still held a body saying
        # both. Judged afresh, it is the collision the binding holds.
        github, issue = self._edited_after_the_lookup(OWN_DESCRIPTION)

        self.deliver(
            github, issue,
            support.verified_message(REUSED_PR, HUMAN_DESCRIPTION),
        )

        self._assert_held_for_a_human(github)
        self.assertNotIn(
            support.CURRENT_RECORD, github.pinned_data(support.REPORT_ISSUE),
        )

    def test_a_description_freed_by_settling_is_named(self) -> None:
        # A report settled on this description earlier; this run's report
        # settles in a comment, which frees it -- and the handoff waits for the
        # two lines to go above it rather than handing on a body closing nothing.
        github, issue, reused = self._reused_over(
            **_settled_on_the_description(),
        )

        self.deliver(github, issue, support.ready_message())

        named, earlier = reused.body.split(EARLIER_HEADING)
        self.assertEqual(
            (
                named.startswith(f"Resolves #{support.REPORT_ISSUE}"),
                earlier.strip(),
                len(support.published_reports(github, REUSED_PR, 2)),
            ),
            (True, HUMAN_DESCRIPTION, 1),
        )
        self.assertIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_description_too_long_to_name_is_held(self) -> None:
        # The two lines would take the description past GitHub's ceiling, and
        # cutting what somebody wrote is not this stage's to do.
        github, issue, reused = self._reused_over()
        reused.body = NEAR_THE_CEILING

        self.deliver(github, issue, support.ready_message())

        self._assert_held_for_a_human(github)
        self.assertEqual(reused.body, NEAR_THE_CEILING)
        self.assertIn(TOO_LONG_NOTICE, issue.comments[-1].body)

    def _assert_held_for_a_human(self, github) -> None:
        """Nothing edited, the work parked for a report, and nothing handed on."""
        pinned = github.pinned_data(support.REPORT_ISSUE)
        self.assertEqual(
            (
                github.edited_pr_bodies,
                pinned.get(AWAITING_HUMAN),
                pinned.get(PARK_REASON),
            ),
            ([], True, _report_delivery.UNDELIVERABLE_REPORT),
        )
        self.assertNotIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )


def _settled_on_the_description() -> dict:
    """The settled pair a report verified on the reused PR's description left."""
    settled = PinnedState()
    _settlement.record_current_report(settled, _records.CurrentReport(
        subject=_records.ReportSubject(
            repo_slug=_TEST_SPEC.slug,
            pr_number=REUSED_PR,
            branch=support.BRANCH,
            source_sha=EARLIER_SHA,
            requirements_revision=support.REQUIREMENTS_REVISION,
        ),
        report_revision=1,
        content_revision=_reports.content_digest(HUMAN_DESCRIPTION),
        location=ReportLocation(pr_number=REUSED_PR),
    ))
    _settlement.record_handoff(settled, _records.ReportHandoff(
        receipt=f"issue-{support.REPORT_ISSUE}-report-1",
        pr_number=REUSED_PR,
        report_revision=1,
        source_sha=EARLIER_SHA,
    ))
    return settled.state_data


class _Unreadable:
    """A pull-request read GitHub leaves unanswered for one number."""

    def __init__(self, number: int, reads) -> None:
        self._number = number
        self._reads = reads

    def __call__(self, number):
        """Read the pull request, unless it is the one nobody can read."""
        if number == self._number:
            raise RuntimeError("GitHub did not answer the pull-request read")
        return self._reads(number)


if __name__ == "__main__":
    unittest.main()
