# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""What one initial publication does with the report its developer wrote.

Across a pull request this tick opens and one already open on the branch, and a
report written for publication or verified on the thread, the report ends up
published and recorded before the issue reaches `validating`. No reused
description is ever edited, and one a report was verified on holds the work
where it does not close the issue and name the session. Every reading is taken
again last, so an edit landing before the relabel holds the work too. The
receipt naming the pull request is durable before any of that, so a process
dying in it leaves the retry holding to that pull request.
`test_report_recovery` covers retries.
"""

from __future__ import annotations

import copy
import itertools
import unittest
from unittest.mock import patch

from orchestrator import config
from orchestrator.github import developer_reports as _reports
from orchestrator.workflow.engine import (
    report_delivery as _report_delivery,
    report_settlement_state as _settlement,
)
from orchestrator.workflow.stages.implementing import report_handoff as _report_handoff
from tests.support.fakes import FakeComment, FakeUser
from tests.workflow.fixtures import (
    _TEST_SPEC,
    LABEL_VALIDATING,
    _named_description,
    _open_pr_for,
)
from tests.workflow.stages.implementing import report_test_support as support

VERIFIED_PR = 55

HUMAN_REPORT_ID = 9100

DESCRIBED_PR = 63

NAMED_PR = 64

# A description a human wrote and a developer then verified as this issue's
# report. It carries no dev-session attribution and no closing reference, and
# nothing here writes them in, so keeping the report there costs this
# publication both.
HUMAN_DESCRIPTION = "### Report\n\nThe branch adds the thing. Verified by hand."

# The same, by a human who wrote what a description alone can say: the merge
# closes the issue, in GitHub's repository-qualified words rather than this
# workflow's, and the line beneath names the session whose branch this is. A
# report verified on it costs the publication nothing.
NAMED_DESCRIPTION = "\n\n".join((
    "### Report",
    "The branch adds the thing. Verified by hand.",
    f"Fixes {support.OWN_SLUG}#{support.REPORT_ISSUE}",
    (
        f"Generated by orchestrator ({config.DEV_AGENT} session "
        f"`{support.DEV_SESSION}`)."
    ),
))

# A description this stage wrote before a report had a place of its own: the
# agent's message under the unmarked heading, and a human's note beneath it that
# nothing can tell apart from that message.
LEGACY_DESCRIPTION = "\n\n".join((
    f"Resolves #{support.REPORT_ISSUE}",
    (
        f"Generated by orchestrator ({config.DEV_AGENT} session "
        f"`{support.DEV_SESSION}`)."
    ),
    "---",
    support.LAST_MESSAGE_HEADING,
    "What an earlier run said it did.",
    "A reviewer's note, added by hand.",
))

LEGACY_PR = 65

FOREIGN_PR = 3

AWAITING_HUMAN = "awaiting_human"

PARK_REASON = "park_reason"

WRITE_PINNED_STATE = "write_pinned_state"

# The pull request the first tick opens: this client numbers them from 1.
OPENED_PR = 1

# The receipt a landed push leaves, and the pull request it names.
PUBLISHED_SHA_KEY = "implementing_published_sha"

PUBLISHED_PR_KEY = "implementing_published_pr"

# Where a publication can die once its pull request is open: the announcement
# of it, whose response is lost, and the handoff, which the process exits in.
ANNOUNCEMENT = "comment"

HANDS_ON = "_hands_on"

ANNOUNCED = ":sparkles: PR opened"

RUN_AGENT = "run_agent"

CLOSED = "closed"

# What this stage wrote on a pull request it opened.
OWN_DESCRIPTION = _named_description(support.REPORT_ISSUE, support.DEV_SESSION)

# Each edit a human can land between the binding and the relabel, by the report
# outcome it lands under, the record whose first write it follows, and what the
# description is replaced with -- or None, appending to where the report stands.
LATE_EDITS = (
    (
        "the settled comment", support.ready_message(),
        support.CURRENT_RECORD, None,
    ),
    (
        "the settled description",
        support.verified_message(NAMED_PR, OWN_DESCRIPTION),
        support.CURRENT_RECORD, None,
    ),
    (
        "the named description", support.ready_message(),
        support.PENDING_RECORD, HUMAN_DESCRIPTION,
    ),
    (
        "the verified description",
        support.verified_message(NAMED_PR, HUMAN_DESCRIPTION),
        support.PENDING_RECORD, HUMAN_DESCRIPTION,
    ),
)


class ReportPublicationTest(unittest.TestCase, support._ReportDeliveryMixin):
    def test_a_new_pr_carries_the_report(self) -> None:
        github, issue = self.seeded()

        self.deliver(github, issue, support.ready_message())

        opened = github.opened_prs[0]
        posted = support.published_reports(github, opened.number)
        self.assertEqual(len(posted), 1)
        self.assertIn(support.REPORT_TEXT, posted[0].body)
        recorded = github.pinned_data(support.REPORT_ISSUE)
        self.assertEqual(
            recorded[support.CURRENT_RECORD],
            {
                "repo": _TEST_SPEC.slug,
                "pr": opened.number,
                "branch": support.BRANCH,
                "sha": support.PUBLISHED_SHA,
                "requirements": recorded["user_content_hash"],
                "revision": 1,
                "content": _reports.content_digest(support.REPORT_TEXT),
                "location_pr": opened.number,
                "location_comment": posted[0].id,
                "mode": "publish",
            },
        )
        self.assertEqual(
            recorded[support.HANDOFF_RECORD],
            {
                "receipt": f"issue-{support.REPORT_ISSUE}-report-1",
                "pr": opened.number,
                "revision": 1,
                "sha": support.PUBLISHED_SHA,
            },
        )
        # Both outstanding records are settled, and the issue only moves on
        # because they are.
        self.assertEqual(
            (
                recorded[support.DELIVERY_RECORD],
                recorded[support.PENDING_RECORD],
            ),
            (None, None),
        )
        self.assertIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )
        # The report comment is the authority, so the description carries what
        # only it can -- the closing reference and the attribution -- and no
        # unmarked, unversioned copy of the report beside it.
        self.assertEqual(
            tuple(
                written in opened.body for written in (
                    f"Resolves #{support.REPORT_ISSUE}",
                    support.DEV_SESSION,
                    support.LAST_MESSAGE_HEADING,
                    support.REPORT_TEXT,
                )
            ),
            (True, True, False, False),
        )

    def test_a_legacy_tail_is_left_intact(self) -> None:
        # The body already names this implementation, so nothing rewrites it:
        # the old tail and the human's note stay exactly where they are, and
        # the report goes out as a comment beside them.
        github, issue = self.seeded()
        reused = _open_pr_for(
            github, issue_number=support.REPORT_ISSUE, pr_number=LEGACY_PR,
        )
        reused.body = LEGACY_DESCRIPTION
        github.existing_open_pr[support.BRANCH] = reused

        self.deliver(github, issue, support.ready_message())

        self.assertEqual(
            (github.edited_pr_bodies, reused.body),
            ([], LEGACY_DESCRIPTION),
        )
        self.assertEqual(len(support.published_reports(github, LEGACY_PR)), 1)
        self.assertIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_verified_report_posts_nothing(self) -> None:
        # The developer read a report a human published and asserted it. The
        # location is re-read rather than believed, and nothing is posted.
        github, issue = self.seeded()
        reused = _open_pr_for(
            github, issue_number=support.REPORT_ISSUE, pr_number=VERIFIED_PR,
            body=_named_description(support.REPORT_ISSUE, support.DEV_SESSION),
        )
        github.existing_open_pr[support.BRANCH] = reused
        human = FakeComment(
            id=HUMAN_REPORT_ID,
            body="the human's own report",
            user=FakeUser("alice"),
        )
        reused.issue_comments.append(human)

        self.deliver(
            github,
            issue,
            support.verified_message(
                reused.number, human.body, comment_id=human.id,
            ),
        )

        self.assertEqual(github.posted_pr_comments, [])
        settled = github.pinned_data(support.REPORT_ISSUE)[
            support.CURRENT_RECORD
        ]
        self.assertEqual(
            (settled["content"], settled["location_comment"]),
            (_reports.content_digest(human.body), human.id),
        )
        self.assertIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_needed_description_is_held(self) -> None:
        # A report verified on a body that neither closes the issue nor names
        # the session: preserved exactly as it stands, and a human is asked.
        github, issue = self.seeded()
        reused = _open_pr_for(
            github, issue_number=support.REPORT_ISSUE, pr_number=DESCRIBED_PR,
        )
        reused.body = HUMAN_DESCRIPTION
        github.existing_open_pr[support.BRANCH] = reused

        self.deliver(
            github,
            issue,
            support.verified_message(reused.number, HUMAN_DESCRIPTION),
        )

        self.assertEqual(github.edited_pr_bodies, [])
        self.assertEqual(reused.body, HUMAN_DESCRIPTION)
        recorded = github.pinned_data(support.REPORT_ISSUE)
        self.assertEqual(
            (recorded.get(AWAITING_HUMAN), recorded.get(PARK_REASON)),
            (True, _report_delivery.UNDELIVERABLE_REPORT),
        )
        # Nothing of the report is discarded: what the run delivered is still
        # recorded, so the reply that resumes the session can place it
        # somewhere this stage can keep.
        self.assertIsNotNone(recorded[support.DELIVERY_RECORD])
        self.assertNotIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_named_description_settles(self) -> None:
        # The same verification onto a body that already closes this issue and
        # names the session: the description costs the publication nothing, and
        # the transaction settles on it.
        github, issue = self.seeded()
        reused = _open_pr_for(
            github, issue_number=support.REPORT_ISSUE, pr_number=NAMED_PR,
        )
        reused.body = NAMED_DESCRIPTION
        github.existing_open_pr[support.BRANCH] = reused

        self.deliver(
            github,
            issue,
            support.verified_message(reused.number, NAMED_DESCRIPTION),
        )

        self.assertEqual(github.edited_pr_bodies, [])
        self.assertEqual(reused.body, NAMED_DESCRIPTION)
        self.assertEqual(github.posted_pr_comments, [])
        settled = github.pinned_data(support.REPORT_ISSUE)[
            support.CURRENT_RECORD
        ]
        self.assertEqual(
            (
                settled["location_pr"],
                settled["location_comment"],
                settled["content"],
            ),
            (
                NAMED_PR,
                None,
                _reports.content_digest(NAMED_DESCRIPTION),
            ),
        )
        self.assertIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_run_with_no_report_publishes_nothing(self) -> None:
        # Every developer prompt teaches the report contract, so a run that
        # finished, committed, and handed over no report is one this stage
        # holds rather than ships: published, a reviewer would be sent an
        # implementation nobody described, with no session left to ask.
        for described, message in (
            ("no marker at all", "implemented, nothing else to say"),
            ("a block nothing closed", "REPORT: READY\nhalf a report"),
            (
                "another repository",
                support.verified_message(
                    FOREIGN_PR, HUMAN_DESCRIPTION, slug=support.FOREIGN_SLUG,
                ),
            ),
        ):
            with self.subTest(message=described):
                github, issue = self.seeded()

                self.deliver(github, issue, message)

                recorded = github.pinned_data(support.REPORT_ISSUE)
                self.assertEqual(
                    (
                        github.opened_prs,
                        recorded.get(AWAITING_HUMAN),
                        recorded.get(PARK_REASON),
                    ),
                    ([], True, _report_delivery.UNDELIVERABLE_REPORT),
                )
                self.assertNotIn(
                    (support.REPORT_ISSUE, LABEL_VALIDATING),
                    github.label_history,
                )



class LateDescriptionTest(unittest.TestCase, support._ReportDeliveryMixin):
    """A publication onto a reused pull request, read afresh at both moments."""

    def test_a_stale_lookup_hides_no_collision(self) -> None:
        # The report was verified on the description as it stands -- closing
        # nothing, naming nobody -- while the lookup still held a body saying
        # both. Judged afresh, it is the collision the binding holds.
        self._reused_over(HUMAN_DESCRIPTION)
        looked_up = copy.copy(self.github.get_pr(NAMED_PR))
        looked_up.body = OWN_DESCRIPTION
        self.github.existing_open_pr[support.BRANCH] = looked_up

        self.deliver(
            self.github, self.issue,
            support.verified_message(NAMED_PR, HUMAN_DESCRIPTION),
        )

        self._assert_held_for_a_human()
        self.assertEqual(self.github.get_pr(NAMED_PR).body, HUMAN_DESCRIPTION)
        self.assertNotIn(
            support.CURRENT_RECORD, self.github.pinned_data(support.REPORT_ISSUE),
        )

    def test_an_edit_before_the_handoff_holds_it(self) -> None:
        # Each reading was true when it was taken, and a human edit lands
        # between the binding and the relabel: the settled report rewritten
        # where it stands, or a named description replaced -- with the report
        # in a comment, or with the very report verified on what replaced it.
        # Read again last, each holds the work, and no description is written.
        for edited, message, *editing in LATE_EDITS:
            with self.subTest(edited=edited):
                self._reused_over(OWN_DESCRIPTION)
                edits = _EditsWhereItStands(self.github, *editing)

                with patch.object(self.github, WRITE_PINNED_STATE, edits):
                    self.deliver(self.github, self.issue, message)

                self.assertTrue(edits.edited)
                self._assert_held_for_a_human()

    def _reused_over(self, description: str) -> None:
        """Seed an issue whose branch has a pull request described so."""
        github, issue = self.seeded()
        github.existing_open_pr[support.BRANCH] = _open_pr_for(
            github, issue_number=support.REPORT_ISSUE, pr_number=NAMED_PR,
            body=description,
        )
        self.github = github
        self.issue = issue

    def _assert_held_for_a_human(self) -> None:
        """Nothing written, the work parked for a report, and nothing handed on."""
        pinned = self.github.pinned_data(support.REPORT_ISSUE)
        self.assertEqual(
            (
                self.github.edited_pr_bodies,
                pinned.get(AWAITING_HUMAN),
                pinned.get(PARK_REASON),
            ),
            ([], True, _report_delivery.UNDELIVERABLE_REPORT),
        )
        self.assertNotIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), self.github.label_history,
        )


class InterruptedHandoffTest(unittest.TestCase, support._ReportDeliveryMixin):
    """A publication that dies once its pull request is open."""

    def test_a_crash_keeps_the_pull_request(self) -> None:
        # The response to the announcement of the pull request is lost, or the
        # process dies as the handoff starts. Either way the receipt naming
        # that pull request is durable already, so the next poll holds to it:
        # finished there while it is open, and while it is closed, no second
        # one is opened and no report goes anywhere.
        for dies_at, closed in itertools.product(
            (ANNOUNCEMENT, HANDS_ON), (False, True),
        ):
            with self.subTest(dies_at=dies_at, closed=closed):
                seeded = self._died_once_opened(dies_at)
                github = seeded[0]
                if closed:
                    github.get_pr(OPENED_PR).state = CLOSED
                    github.existing_open_pr.pop(support.BRANCH)

                self.republish(*seeded)[RUN_AGENT].assert_not_called()

                self._assert_kept(github, closed=closed)

    def _assert_kept(self, github, *, closed: bool) -> None:
        """One pull request only, finished there unless it was closed."""
        self.assertEqual(
            (
                len(github.opened_prs),
                [number for number, _ in github.posted_pr_comments],
                [label for _, label in github.label_history],
            ),
            (
                1,
                [] if closed else [OPENED_PR],
                [] if closed else [LABEL_VALIDATING],
            ),
        )

    def _died_once_opened(self, dies_at: str):
        """A tick that dies at `dies_at`, once its pull request is open."""
        seeded = self.seeded()
        github = seeded[0]
        dies = patch.object(
            github, ANNOUNCEMENT, _LosesTheAnnouncement(github.comment),
        ) if dies_at == ANNOUNCEMENT else patch.object(
            _report_handoff, HANDS_ON, side_effect=SystemExit,
        )
        with dies, self.assertRaises((_LostResponseError, SystemExit)):
            self.deliver(*seeded, support.ready_message())
        recorded = github.pinned_data(support.REPORT_ISSUE)
        self.assertEqual(
            (recorded[PUBLISHED_SHA_KEY], recorded[PUBLISHED_PR_KEY]),
            (support.PUBLISHED_SHA, OPENED_PR),
        )
        github.get_pr(OPENED_PR).head.sha = support.PUBLISHED_SHA
        return seeded


class _LostResponseError(RuntimeError):
    """A request GitHub carried out whose answer never came back."""


class _LosesTheAnnouncement:
    """Post each issue comment, losing the answer to the pull request's one."""

    def __init__(self, comment) -> None:
        self._comment = comment

    def __call__(self, issue, body: str):
        """Post the comment, then fail the tick if it announced the PR."""
        posted = self._comment(issue, body)
        if ANNOUNCED in body:
            raise _LostResponseError(body)
        return posted


class _EditsWhereItStands:
    """A pinned write after which a human edits the reused pull request.

    Once, after the first write carrying `record`: the description is replaced
    with `rewritten` where one is given, and otherwise the settled report is
    appended to where it stands.
    """

    def __init__(self, github, record: str, rewritten: str | None) -> None:
        self._github = github
        self._wrote = github.write_pinned_state
        self._record = record
        self._rewritten = rewritten
        self.edited = False

    def __call__(self, issue, state):
        """Write, then make the edit once the record is first written."""
        written = self._wrote(issue, state)
        if state.get(self._record) and not self.edited:
            self.edited = True
            self._edits(state)
        return written

    def _edits(self, state) -> None:
        """Replace the description, or append to the settled report."""
        pull = self._github.get_pr(NAMED_PR)
        if self._rewritten is not None:
            pull.body = self._rewritten
            return
        comment_id = _settlement.read_current_report(state).location.comment_id
        stands_on = pull if comment_id is None else next(
            posted for posted in pull.issue_comments if posted.id == comment_id
        )
        stands_on.body = f"{stands_on.body}\n\nEdited once it settled."

if __name__ == "__main__":
    unittest.main()
