# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""What a reused pull request's description keeps, and when it holds the work.

The description is judged as it stands NOW, read afresh, and a body that does
not name this implementation gets the two lines above it with every word kept.
`test_report_publication` covers the bodies left alone because of what they SAY.
"""

from __future__ import annotations

import copy
import unittest
from types import MappingProxyType
from unittest.mock import patch

from orchestrator import config
from orchestrator.github import developer_reports as _reports
from orchestrator.github.pinned_state import MAX_PINNED_BODY, PinnedState
from orchestrator.github.pull_request_reports import ReportLocation
from orchestrator.workflow.engine import (
    report_delivery as _report_delivery,
    report_records as _records,
    report_settlement_state as _settlement,
)
from tests.workflow.fixtures import (
    _TEST_SPEC,
    LABEL_VALIDATING,
    SHA_LENGTH,
    _open_pr_for,
)
from tests.workflow.stages.implementing import report_test_support as support

REUSED_PR = 71

# What a human wrote over the body: no closing reference, no attribution.
HUMAN_DESCRIPTION = "### Notes\n\nRewritten by hand, and meant to stay."

# What the body said when the lookup fetched it, before that edit landed.
LOOKED_UP_DESCRIPTION = "### Plan\n\nThe description the lookup fetched."

# What this stage wrote on a pull request it opened: the closing reference and
# the session, which is everything a reuse leaves alone.
OWN_DESCRIPTION = (
    f"Resolves #{support.REPORT_ISSUE}\n\n"
    f"Generated by orchestrator ({config.DEV_AGENT} session "
    f"`{support.DEV_SESSION}`)."
)

EARLIER_HEADING = "_Description before this implementation:_"

# This stage's own description with its closing reference shown only as code.
QUOTED_REFERENCES = (
    OWN_DESCRIPTION.replace("Resolves", "```\nResolves", 1).replace(
        "\n\nGenerated", "\n```\n\nGenerated", 1,
    ),
    OWN_DESCRIPTION.replace(
        f"Resolves #{support.REPORT_ISSUE}",
        f"Write `Resolves #{support.REPORT_ISSUE}` to close it.",
    ),
)

GET_PR = "get_pr"

WRITE_PINNED_STATE = "write_pinned_state"

AWAITING_HUMAN = "awaiting_human"

PARK_REASON = "park_reason"

# A commit an earlier publication of this issue's settled its report about.
EARLIER_SHA = "e" * SHA_LENGTH

# A description a few characters under GitHub's ceiling, which the two lines
# this implementation needs above it would take past that ceiling.
NEAR_THE_CEILING = "x" * (MAX_PINNED_BODY - 10)

# What the notice for that description says, and no other notice does.
TOO_LONG_NOTICE = "too long to have this issue's closing reference"

# A record whose location still names the reused pull request's description
# while the rest of it will not read.
DAMAGED_RECORD = MappingProxyType({
    "location_pr": REUSED_PR,
    "location_comment": None,
    "revision": "damaged",
})


class _ReusedPullRequest(support._ReportDeliveryMixin):
    """A human's pull request already open on the branch this issue pushes."""

    def _reused_over(self, description: str = HUMAN_DESCRIPTION, **pinned):
        """An issue carrying `pinned`, with a pull request described on its branch."""
        github, issue = self.seeded()
        github.seed_state(support.REPORT_ISSUE, **pinned)
        reused = _open_pr_for(
            github, issue_number=support.REPORT_ISSUE, pr_number=REUSED_PR,
        )
        reused.body = description
        github.existing_open_pr[support.BRANCH] = reused
        return github, issue, reused

    def _edited_after_the_lookup(self, fetched: str):
        """A reused pull request a human edited after the lookup's snapshot."""
        github, issue, live = self._reused_over()
        looked_up = copy.copy(live)
        looked_up.body = fetched
        github.existing_open_pr[support.BRANCH] = looked_up
        return github, issue


class DescriptionGuardTest(unittest.TestCase, _ReusedPullRequest):
    def test_an_edit_after_the_lookup_is_kept(self) -> None:
        # A human replaced the body after the lookup fetched it -- a plan's, or
        # this stage's own complete one. Judged afresh, what they wrote stays
        # beneath this implementation's lines instead of being overwritten or
        # handed to review closing nothing.
        for looked_up in (LOOKED_UP_DESCRIPTION, OWN_DESCRIPTION):
            with self.subTest(looked_up=looked_up):
                github, issue = self._edited_after_the_lookup(looked_up)

                self.deliver(github, issue, support.ready_message())

                self.assertEqual(len(github.edited_pr_bodies), 1)
                named, earlier = github.edited_pr_bodies[0][1].split(
                    EARLIER_HEADING,
                )
                self.assertEqual(
                    (
                        named.startswith(f"Resolves #{support.REPORT_ISSUE}"),
                        support.DEV_SESSION in named,
                        support.LAST_MESSAGE_HEADING in named,
                        earlier.strip(),
                        len(support.published_reports(github, REUSED_PR)),
                        github.pinned_data(support.REPORT_ISSUE)[
                            support.CURRENT_RECORD
                        ]["pr"],
                    ),
                    (True, True, False, HUMAN_DESCRIPTION, 1, REUSED_PR),
                )
                self.assertIn(
                    (support.REPORT_ISSUE, LABEL_VALIDATING),
                    github.label_history,
                )

    def test_an_unreadable_description_holds(self) -> None:
        # Nothing is written over a description nobody could read, and nothing
        # is handed on: the commit stays owed for the next tick.
        github, issue, reused = self._reused_over()

        with patch.object(github, GET_PR, _Unreadable(REUSED_PR, github.get_pr)):
            self.deliver(github, issue, support.ready_message())

        self.assertEqual(
            (github.edited_pr_bodies, reused.body), ([], HUMAN_DESCRIPTION),
        )
        self.assertEqual(support.published_reports(github, REUSED_PR), [])
        self.assertNotIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_damaged_record_keeps_the_description(self) -> None:
        # A damaged record may still name the description -- a delivery or a
        # current report whose own fields will not read, a current report
        # nulled beside its handoff, or a handoff left on its own -- so the
        # body stays, the records stay, and the work is not handed on.
        for damaged in _damaged_claims():
            with self.subTest(damaged=sorted(damaged)):
                github, issue, reused = self._reused_over(
                    dev_session_id=support.DEV_SESSION, **damaged,
                )

                if support.DELIVERY_RECORD in damaged:
                    self.republish(github, issue)
                else:
                    self._delivers(github, issue)

                pinned = github.pinned_data(support.REPORT_ISSUE)
                self.assertEqual(
                    (
                        github.edited_pr_bodies,
                        reused.body,
                        {key: pinned.get(key) for key in damaged},
                    ),
                    ([], HUMAN_DESCRIPTION, damaged),
                )
                self.assertNotIn(
                    (support.REPORT_ISSUE, LABEL_VALIDATING),
                    github.label_history,
                )

    def test_a_quoted_reference_closes_nothing(self) -> None:
        # A closing reference shown as code -- fenced, or inline -- is literal
        # text GitHub does not act on, so the body still earns the real one.
        for quoted in QUOTED_REFERENCES:
            with self.subTest(quoted=quoted):
                github, issue, reused = self._reused_over()
                reused.body = quoted

                self.deliver(github, issue, support.ready_message())

                self.assertEqual(
                    (
                        reused.body.startswith(f"Resolves #{support.REPORT_ISSUE}"),
                        reused.body.endswith(f"{EARLIER_HEADING}\n\n{quoted}"),
                    ),
                    (True, True),
                )

    def _delivers(self, github, issue):
        """Run the ordinary tick, whose developer reports for publication."""
        return self.deliver(github, issue, support.ready_message())


class DescriptionHoldTest(unittest.TestCase, _ReusedPullRequest):
    """The descriptions a publication may not be handed on under."""

    def test_a_stale_lookup_hides_no_collision(self) -> None:
        # The report was verified on the description as it stands -- closing
        # nothing, naming nobody -- while the lookup still held a body saying
        # both. Judged afresh, it is the collision the binding holds.
        github, issue = self._edited_after_the_lookup(OWN_DESCRIPTION)

        self.deliver(
            github, issue,
            support.verified_message(REUSED_PR, HUMAN_DESCRIPTION),
        )

        self._assert_held_for_a_human(github)
        self.assertNotIn(
            support.CURRENT_RECORD, github.pinned_data(support.REPORT_ISSUE),
        )

    def test_a_description_freed_by_settling_is_named(self) -> None:
        # A report settled on this description earlier; this run's report
        # settles in a comment, which frees it -- and the handoff waits for the
        # two lines to go above it rather than handing on a body closing nothing.
        github, issue, reused = self._reused_over(
            **_settled_on_the_description(),
        )

        self.deliver(github, issue, support.ready_message())

        named, earlier = reused.body.split(EARLIER_HEADING)
        self.assertEqual(
            (
                named.startswith(f"Resolves #{support.REPORT_ISSUE}"),
                earlier.strip(),
                len(support.published_reports(github, REUSED_PR, 2)),
            ),
            (True, HUMAN_DESCRIPTION, 1),
        )
        self.assertIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )

    def test_a_description_too_long_to_name_is_held(self) -> None:
        # The two lines would take the description past GitHub's ceiling, and
        # cutting what somebody wrote is not this stage's to do.
        github, issue, reused = self._reused_over()
        reused.body = NEAR_THE_CEILING

        self.deliver(github, issue, support.ready_message())

        self._assert_held_for_a_human(github)
        self.assertEqual(reused.body, NEAR_THE_CEILING)
        self.assertIn(TOO_LONG_NOTICE, issue.comments[-1].body)

    def test_a_report_edited_once_settled_is_held(self) -> None:
        # A settlement is one moment. A human editing the report the moment
        # after -- the description it was verified on, or the comment it was
        # published as -- leaves review a report that is not the one recorded,
        # so it is read again before the handoff and the work parks.
        for message in (
            support.verified_message(REUSED_PR, OWN_DESCRIPTION),
            support.ready_message(),
        ):
            with self.subTest(message=message):
                github, issue = self._reused_over(OWN_DESCRIPTION)[:2]
                editing = _EditsWhereItStands(github)

                with patch.object(github, WRITE_PINNED_STATE, editing):
                    self.deliver(github, issue, message)

                self.assertTrue(editing.edited)
                self._assert_held_for_a_human(github)

    def test_a_description_rewritten_late_is_held(self) -> None:
        # Judged, the description named this implementation; rewritten into
        # the very report verified on it before that report settled there. The
        # report stands and nothing is owed, so no retry frees the description
        # and the work parks for a report-only reply.
        github, issue = self._reused_over(OWN_DESCRIPTION)[:2]
        editing = _EditsWhereItStands(
            github, support.PENDING_RECORD, HUMAN_DESCRIPTION,
        )

        with patch.object(github, WRITE_PINNED_STATE, editing):
            self.deliver(
                github, issue,
                support.verified_message(REUSED_PR, HUMAN_DESCRIPTION),
            )

        self.assertIn(
            support.CURRENT_RECORD, github.pinned_data(support.REPORT_ISSUE),
        )
        self._assert_held_for_a_human(github)

    def _assert_held_for_a_human(self, github) -> None:
        """Nothing edited, the work parked for a report, and nothing handed on."""
        pinned = github.pinned_data(support.REPORT_ISSUE)
        self.assertEqual(
            (
                github.edited_pr_bodies,
                pinned.get(AWAITING_HUMAN),
                pinned.get(PARK_REASON),
            ),
            ([], True, _report_delivery.UNDELIVERABLE_REPORT),
        )
        self.assertNotIn(
            (support.REPORT_ISSUE, LABEL_VALIDATING), github.label_history,
        )


def _damaged_claims() -> tuple:
    """Every damaged record that may still claim the reused PR's description."""
    settled = _settled_on_the_description()
    return (
        {support.DELIVERY_RECORD: dict(DAMAGED_RECORD)},
        {support.CURRENT_RECORD: dict(DAMAGED_RECORD)},
        {**settled, support.CURRENT_RECORD: None},
        {support.HANDOFF_RECORD: settled[support.HANDOFF_RECORD]},
    )


def _settled_on_the_description() -> dict:
    """The settled pair a report verified on the reused PR's description left."""
    settled = PinnedState()
    _settlement.record_current_report(settled, _records.CurrentReport(
        subject=_records.ReportSubject(
            repo_slug=_TEST_SPEC.slug,
            pr_number=REUSED_PR,
            branch=support.BRANCH,
            source_sha=EARLIER_SHA,
            requirements_revision=support.REQUIREMENTS_REVISION,
        ),
        report_revision=1,
        content_revision=_reports.content_digest(HUMAN_DESCRIPTION),
        location=ReportLocation(pr_number=REUSED_PR),
    ))
    _settlement.record_handoff(settled, _records.ReportHandoff(
        receipt=f"issue-{support.REPORT_ISSUE}-report-1",
        pr_number=REUSED_PR,
        report_revision=1,
        source_sha=EARLIER_SHA,
    ))
    return settled.state_data


class _EditsWhereItStands:
    """A pinned write after which a human edits where one report record stands.

    Once, after the first write carrying `record`: the text is appended to, or
    replaced with `rewritten` where one is given.
    """

    def __init__(
        self, github, record=support.CURRENT_RECORD, rewritten=None,
    ) -> None:
        self._github = github
        self._wrote = github.write_pinned_state
        self._record = record
        self._rewritten = rewritten
        self.edited = False

    def __call__(self, issue, state):
        """Write, then edit the location the written record names, once."""
        written = self._wrote(issue, state)
        recorded = state.get(self._record)
        if recorded and not self.edited:
            self.edited = True
            pull = self._github.get_pr(recorded["location_pr"])
            stands_on = pull if recorded["location_comment"] is None else next(
                posted for posted in pull.issue_comments
                if posted.id == recorded["location_comment"]
            )
            stands_on.body = self._rewritten or (
                f"{stands_on.body}\n\nEdited once it settled."
            )
        return written


class _Unreadable:
    """A pull-request read GitHub leaves unanswered for one number."""

    def __init__(self, number: int, reads) -> None:
        self._number = number
        self._reads = reads

    def __call__(self, number):
        """Read the pull request, unless it is the one nobody can read."""
        if number == self._number:
            raise RuntimeError("GitHub did not answer the pull-request read")
        return self._reads(number)


if __name__ == "__main__":
    unittest.main()
